# Generated by Django 3.1.7 on 2021-03-08 01:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path, verbose_name='profile picture'),
        ),
    ]
