# Generated by Django 3.1.7 on 2021-03-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210309_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile picture'),
        ),
    ]
