# Generated by Django 3.1.7 on 2021-02-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210226_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('id',)},
        ),
    ]
